name: vetcomm
description: "vetcomm"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  #  youtube video player
  youtube_player_iframe: ^5.1.5

flutter:
  uses-material-design: true
