name: vetcomm
description: "vetcomm"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  #  facebook sign in
  flutter_facebook_auth: ^7.1.1


flutter:
  uses-material-design: true
